### ISSUE TITLE
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.FloatingActionButton.setOnClickListener(android.view.View$OnClickListener)' on a null object reference

### ISSUE THREAD

**Issue by tabish075** [erikagtierrez/multiple-media-picker#13]
Iam using `compile 'com.android.support:design:26.1.0'` but still getting this error

` java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.tabish.vault/com.erikagtierrez.multiple_media_picker.Gallery}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.FloatingActionButton.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                              at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                              at android.os.Looper.loop(Looper.java:156)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                           Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.FloatingActionButton.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                              at com.erikagtierrez.multiple_media_picker.Gallery.onCreate(Gallery.java:53)
                                                                              at android.app.Activity.performCreate(Activity.java:6910)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
                                                                              at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                              at android.os.Looper.loop(Looper.java:156) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6523) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) `

**Comment by erikagtierrez** [comment]
What library version are you using? I'm afraid you're not using the last one.. This is a v1.0.1 error 😄 
Let me know!

**Comment by tabish075** [comment]
Thanks for replying and yes it is resolved i was using 1.0.1 my bad :)
