### ISSUE TITLE
Java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bitstobyte.performalux/com.erikagtierrez.multiple_media_picker.Gallery}:  				android.view.InflateException: Binary XML file line #0: Failed to resolve attribute at index 6: TypedValue{t=0x1c/d=0xff000000 a=1 r=0x106000c}

### ISSUE THREAD

**Issue by aana77** [erikagtierrez/multiple-media-picker#17]
I am getting the following error

FATAL EXCEPTION: main
                                                                          Process: com.bitstobyte.performalux, PID: 27350
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bitstobyte.performalux/com.erikagtierrez.multiple_media_picker.Gallery}: android.view.InflateException: Binary XML file line #0: Failed to resolve attribute at index 6: TypedValue{t=0x1c/d=0xff000000 a=1 r=0x106000c}
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667)
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                at android.os.Looper.loop(Looper.java:207)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5776)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                             Caused by: android.view.InflateException: Binary XML file line #0: Failed to resolve attribute at index 6: TypedValue{t=0x1c/d=0xff000000 a=1 r=0x106000c}
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                at com.erikagtierrez.multiple_media_picker.Gallery.onCreate(Gallery.java:40)
                                                                                at android.app.Activity.performCreate(Activity.java:6582)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667) 
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                at android.os.Looper.loop(Looper.java:207) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5776) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                             Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x1c/d=0xff000000 a=1 r=0x106000c}
                                                                                at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:705)
                                                                                at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:7094)
                                                                                at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7275)
                                                                                at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:2169)
                                                                                at android.support.design.widget.AppBarLayout$LayoutParams.<init>(AppBarLayout.java:681)
                                                                                at android.support.design.widget.AppBarLayout.generateLayoutParams(AppBarLayout.java:336)
                                                                                at android.support.design.widget.AppBarLayout.generateLayoutParams(AppBarLayout.java:106)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                                at com.erikagtierrez.multiple_media_picker.Gallery.onCreate(Gallery.java:40) 
                                                                                at android.app.Activity.performCreate(Activity.java:6582) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667) 
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                at android.os.Looper.loop(Looper.java:207) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5776) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by erikagtierrez** [comment]
Hey! Which version are you using? It seems to be a v1.0.1 error
