### ISSUE TITLE
[Deprecated] Glide 4.X.X Error

### ISSUE THREAD

**Issue by anibalbastiass** [erikagtierrez/multiple-media-picker#19]
When I trying to use this library, returns this exception:

```
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/{PACKAGE-APP}-uZOsLz-sVM9B8EQjvcbAHQ==/split_lib_dependencies_apk.apk:classes2.dex)
                                                       at com.erikagtierrez.multiple_media_picker.Adapters.BucketsAdapter.onBindViewHolder(BucketsAdapter.java:49)
                                                       at com.erikagtierrez.multiple_media_picker.Adapters.BucketsAdapter.onBindViewHolder(BucketsAdapter.java:17)
                                                       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
                                                       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                       at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                       at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3135)
                                                       at android.view.View.measure(View.java:22002)
                                                       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                       at android.view.View.measure(View.java:22002)
                                                       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1632)
                                                       at android.view.View.measure(View.java:22002)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:719)
                                                       at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
                                                       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1361)
                                                       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:789)
                                                       at android.view.View.measure(View.java:22002)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                       at android.view.View.measure(View.java:22002)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
                                                       at android.view.View.measure(View.java:22002)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                       at android.view.View.measure(View.java:22002)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
                                                       at android.view.View.measure(View.java:22002)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6580)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
02-23 11:06:22.335 28833-28833/? E/AndroidRuntime:     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:721)
                                                       at android.view.View.measure(View.java:22002)
                                                       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2410)
                                                       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1498)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1751)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                       at android.os.Handler.handleCallback(Handler.java:789)
                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

In summary, this library needs upgrade Glide 3.X.X to 4.X.X. Greetings.

**Comment by WrathChaos** [comment]
I have the same issue, please upgrade it.

**Comment by erikagtierrez** [comment]
Can you please try with the new version 1.0.5 ? 😄
