### ISSUE TITLE
Index out of bound Exception

### ISSUE THREAD

**Issue by manojm95** [erikagtierrez/multiple-media-picker#5]
Random times when i try to open a folder I get the below error The probability of getting this error is one out of three or four times, when I try to open a folder. Device is Samsung

03-03 19:59:29.189 19420-19420/com.example.manojprabahar.imagepickerimage E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                            Process: com.example.manojprabahar.imagepickerimage, PID: 19420
                                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.manojprabahar.imagepickerimage/com.erikagtierrez.multiple_media_picker.OpenGallery}: java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
                                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3320)
                                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3416)
                                                                                                at android.app.ActivityThread.access$1100(ActivityThread.java:230)
                                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1822)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:7409)
                                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                                             Caused by: java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
                                                                                                at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                                at java.util.ArrayList.get(ArrayList.java:308)
                                                                                                at com.erikagtierrez.multiple_media_picker.OpenGallery.populateRecyclerView(OpenGallery.java:75)
                                                                                                at com.erikagtierrez.multiple_media_picker.OpenGallery.onCreate(OpenGallery.java:69)
                                                                                                at android.app.Activity.performCreate(Activity.java:6904)
                                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3267)
                                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3416) 
                                                                                                at android.app.ActivityThread.access$1100(ActivityThread.java:230) 
                                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1822) 
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:7409) 
                                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by jmarkstar** [comment]
+1

**Comment by Gwindor-Aut** [comment]
+1

**Comment by erikagtierrez** [comment]
Make sure you're using the last version:
` compile 'com.erikagtierrez.multiple_media_picker:multiple-media-picker:1.0.2' 
`
And let me know if the problem persists
